version: '3.8'

services:
  db2:
    image: postgres:13
    restart: always
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=de_projects

    ports:
      - '5436:5436'
    volumes:
      - db:/var/lib/postgresql/data

volumes:
  db:
    driver: local
